#!/bin/bash
echo "📊 检查部署状态..."
echo ""
echo "1️⃣  访问: https://github.com/JohnsonGAOK/superstore-sales-dashboard/actions"
echo "   查看 Actions 标签页，等待绿色的 ✓ 标记"
echo ""
echo "2️⃣  部署完成后访问:"
echo "   https://johnsongaok.github.io/superstore-sales-dashboard/"
echo ""
echo "3️⃣  使用快捷键强制刷新:"
echo "   • macOS: Command + Shift + R"
echo "   • Windows: Ctrl + Shift + R"
echo ""
open "https://github.com/JohnsonGAOK/superstore-sales-dashboard/actions"
